Repository aidudezzz/deepworlds, pull requests merged in 2022-06, with the labels that each got.

#63 Find_and_Avoid - fix coordinate system
  examples/find_and_avoid/controllers/supervisor/utilities.py
  examples/find_and_avoid/worlds/small_world.wbt
Labels: refactor

#56 Pit Escape fixes and new reset procedure
  examples/pit_escape/pit_escape_discrete/controllers/robot_controller/robot_controller.py
  examples/pit_escape/pit_escape_discrete/controllers/supervisor_manager/BB-8.wbo
  examples/pit_escape/pit_escape_discrete/controllers/supervisor_manager/PPO_runner.py
  examples/pit_escape/pit_escape_discrete/controllers/supervisor_manager/supervisor_controller.py
  examples/pit_escape/pit_escape_discrete/controllers/supervisor_manager/utilities.py
  examples/pit_escape/pit_escape_discrete/worlds/pit_escape.wbt
Labels: bug, refactor

#72 Fixed broken links in CartPole README
  examples/cartpole/README.md
Labels: documentation

#71 Discrete CartPole Robot-Supervisor SB3 - fix coordinate system
  examples/cartpole/cartpole_discrete/controllers/robot_supervisor_manager_Stable_Baselines/robot_supervisor.py
  examples/cartpole/cartpole_discrete/worlds/cartPoleWorldRobotSupervisorStableBaselines.wbt
Labels: refactor
